# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://kylerrussell.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Kyler Russell
# Description of the Site
description: Thanks for checking out my site. I created this site to display my projects, information, and blog posts. 
# URL of Image of the Site
site-image: 
# Keywords of the Site
site-keywords: Portfolio
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://kylerrussell.github.io/assets/images/engineeringdrawing.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: kylerussell@protonmail.com
phone: 913-337-6518
#facebook_username: /
#twitter_username: /
#instagram_username: /
linkedin_username: kyler-russell
github_username:  KylerRussell
#youtube_channel_id: /
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: Kyler Russell

# Name of the Author
author-name: Kyler Russell
# URL for the Image of the Author
author-image: https://kylerrussell.github.io/assets/images/me.jpg
# 60 Words About the Author
author-about: I'm Kyler Russell, a senior at Olathe Northwest in the Engineering Academy with a passion for cybersecurity, programming, and networking. I am a CyberPatriot XV National Finalist and looking forward to continue exploring the field of cybersecurity and computer science in college.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/kyler-russell/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
